  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"
      networks:
        - qdrant-network

    kafka:
      image: confluentinc/cp-kafka:7.4.0
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      networks:
        - qdrant-network

    kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - 8080:8080
      networks:
        - qdrant-network
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092  # Use internal port
      depends_on:
        - kafka


    python-app:
      build: .
      container_name: python-app
      volumes:
        - .:/app
      working_dir: /app
      ports:
        - "8501:8501"
      depends_on:
        - qdrant
      networks:
        - qdrant-network
      environment:
        - QDRANT_URL=http://qdrant:6333
      command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
      restart: unless-stopped

    qdrant:
      image: qdrant/qdrant:latest
      container_name: qdrant
      restart: unless-stopped
      ports:
        - "6333:6333"
        - "6334:6334"
      volumes:
        - qdrant_data:/qdrant/storage
      environment:
        - QDRANT__LOG_LEVEL=INFO
        - QDRANT__SERVICE__HTTP_PORT=6333
        - QDRANT__SERVICE__GRPC_PORT=6334
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
        interval: 30s
        timeout: 10s
        retries: 3
      networks:
        - qdrant-network

  networks:
    qdrant-network:
      driver: bridge

  volumes:
    qdrant_data:
      driver: local
