version: '3.8'
services:
  python-app:
    build: .
    container_name: python-app
    volumes:
      - .:/app  # Mount to /app directory (matches Dockerfile)
    working_dir: /app
    command: tail -f /dev/null  # For development/debugging
    depends_on:
      - qdrant
    networks:
      - qdrant-network
    environment:
      - QDRANT_URL=http://qdrant:6333  # Service discovery

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - qdrant-network

networks:
  qdrant-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local