services:
  python-app:
    build: .
    container_name: python-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"  # Expose Streamlit port
    depends_on:
      - qdrant
    networks:
      - qdrant-network
    environment:
      - QDRANT_URL=http://qdrant:6333
    # Add this command to automatically run Streamlit
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
    # Optional: Add restart policy
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - qdrant-network

networks:
  qdrant-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
